package liczydło;
 
import java.util.*;
import java.io.*;
import java.lang.String.*;
 
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.UIManager;
 
import com.jtattoo.plaf.aero.AeroLookAndFeel;
 
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Dimension;
 
/**
 * @author Gjorni
 */
public class kalkulator extends javax.swing.JFrame
{
    /**
     * Creates new form KalkulatorUI
     */
    public kalkulator()
    {
        initComponents();
        jPanel1.setVisible(true);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton38 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
 
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulatorek");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new Dimension(500, 510));
        setResizable(false);
       
        
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(520, 650));
 
        
        jButton1.setText("0");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
 
        
        jButton4.setText("3");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });
 
        
        jButton5.setText("4");
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });
 
        
        jButton6.setText("5");
        jButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton6ActionPerformed(evt);
            }
        });
 
        
        jButton7.setText("6");
        jButton7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton7ActionPerformed(evt);
            }
        });
 
        
        jButton8.setText("7");
        jButton8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton8ActionPerformed(evt);
            }
        });
 
        
        jButton9.setText("8");
        jButton9.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton9ActionPerformed(evt);
            }
        });
 
        
        jButton10.setText("9");
        jButton10.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton10ActionPerformed(evt);
            }
        });
 
        
        jButton12.setText("/");
        jButton12.setMaximumSize(new java.awt.Dimension(39, 23));
        jButton12.setMinimumSize(new java.awt.Dimension(39, 23));
        jButton12.setPreferredSize(new java.awt.Dimension(41, 23));
        jButton12.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton12ActionPerformed(evt);
            }
        });
 
        
        jButton13.setText("*");
        jButton13.setPreferredSize(new java.awt.Dimension(41, 23));
        jButton13.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton13ActionPerformed(evt);
            }
        });
 
        
        jButton14.setText("-");
        jButton14.setMaximumSize(new java.awt.Dimension(39, 23));
        jButton14.setMinimumSize(new java.awt.Dimension(39, 23));
        jButton14.setPreferredSize(new java.awt.Dimension(41, 23));
        jButton14.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton14ActionPerformed(evt);
            }
        });
 
        
        jButton15.setText("+");
        jButton15.setMaximumSize(new java.awt.Dimension(39, 23));
        jButton15.setMinimumSize(new java.awt.Dimension(39, 23));
        jButton15.setPreferredSize(new java.awt.Dimension(43, 23));
        jButton15.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton15ActionPerformed(evt);
            }
        });
 
        
        jButton16.setText("=");
        jButton16.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton16ActionPerformed(evt);
            }
        });
 
        
        jButton17.setText("sqrt");
        jButton17.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton17ActionPerformed(evt);
            }
        });
 
        
        jButton18.setText("%");
        jButton18.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton18ActionPerformed(evt);
            }
        });
 
        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
 
        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
       
        jButton11.setBackground(new java.awt.Color(255, 102, 102));
        jButton11.setText("CE");
        jButton11.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton11ActionPerformed(evt);
            }
        });
 
        
        jButton20.setText("(");
        jButton20.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton20ActionPerformed(evt);
            }
        });
 
        
        jButton21.setText(")");
        jButton21.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton21ActionPerformed(evt);
            }
        });
 
        jTextField4.setEditable(false);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
 
        jLabel4.setText("ONP");
 
        
        jButton19.setText("C");
        jButton19.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton19ActionPerformed(evt);
            }
        });
 
        
        jButton24.setText("1");
        jButton24.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton24ActionPerformed(evt);
            }
        });
 
        
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
 
        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
 
        
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton3.setText("Del");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
 
        
        jButton25.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton25.setText(".");
        jButton25.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton25ActionPerformed(evt);
            }
        });
 
        
        jButton26.setText("Sin");
        jButton26.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton26ActionPerformed(evt);
            }
        });
 
        
        jButton27.setText("Cos");
        jButton27.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton27ActionPerformed(evt);
            }
        });
 
        
        jButton28.setText("Tan");
        jButton28.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton28ActionPerformed(evt);
            }
        });
 
        
        jButton29.setText("TanH");
        jButton29.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton29ActionPerformed(evt);
            }
        });
 
        
        jButton30.setText("Pi");
        jButton30.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton30ActionPerformed(evt);
            }
        });
 
        
        jButton31.setText("Exp");
        jButton31.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton31ActionPerformed(evt);
            }
        });
 
        
        jButton32.setText("Log");
        jButton32.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton32ActionPerformed(evt);
            }
        });
 
        
        jButton33.setText("Mod");
        jButton33.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton33ActionPerformed(evt);
            }
        });
 
 
        jButton37.setText("x^");
        jButton37.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton37ActionPerformed(evt);
            }
        });
 
        jTextField10.setEditable(false);
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField10.setText("pusta");
 
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pami\u0119\u0107");
 
        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("Rad");
 
        jButton38.setBackground(new java.awt.Color(153, 255, 255));
        jButton38.setText("Rad");
        jButton38.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton38ActionPerformed(evt);
            }
        });
 
        jToggleButton2.setBackground(new java.awt.Color(153, 255, 255));
        jToggleButton2.setText("Deg");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButton2ActionPerformed(evt);
            }
        });
 
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel4)
                                                                                .addPreferredGap(ComponentPlacement.RELATED)
                                                                                .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, 252, GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(jTextField1)))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(10)
                                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
                                                                                        .addComponent(jButton20, GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                                                                        .addComponent(jButton13, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                .addGap(6)
                                                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
                                                                                        .addComponent(jButton21, GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                                                                        .addComponent(jButton12, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                .addGap(6)
                                                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
                                                                                        .addComponent(jButton17, GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                                                                        .addComponent(jButton14, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                .addPreferredGap(ComponentPlacement.RELATED)
                                                                                .addComponent(jButton15, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addComponent(jButton8, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(6)
                                                                                                .addComponent(jButton9, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(ComponentPlacement.RELATED)
                                                                                                .addComponent(jButton10, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
                                                                                                        .addComponent(jButton25, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
                                                                                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                                                                                .addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jButton24, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)))
                                                                                                .addGap(6)
                                                                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
                                                                                                        .addComponent(jButton6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                        .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                        .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE))
                                                                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                .addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                .addComponent(jButton4, GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                .addGap(6)
                                                                                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
                                                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                .addGap(2)
                                                                                                                                .addComponent(jButton19, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                                                        .addComponent(jButton7, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE))))))
                                                                                .addPreferredGap(ComponentPlacement.RELATED)
                                                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
                                                                                        .addComponent(jButton11, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(jButton3, GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))))
                                                                .addPreferredGap(ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                                        .addComponent(jButton18, GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                                                        .addComponent(jButton16, GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))))
                                                .addPreferredGap(ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
                                                        .addComponent(jButton38, GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                                        .addComponent(jButton26, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                                        .addComponent(jLabel7, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                                        .addComponent(jButton29, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton32, GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                                                .addPreferredGap(ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jButton30, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(ComponentPlacement.RELATED)
                                                                .addComponent(jButton31, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jButton37, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(ComponentPlacement.RELATED)
                                                                        .addComponent(jButton33, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(ComponentPlacement.RELATED))
                                                                .addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                        .addGap(0, 1, Short.MAX_VALUE)
                                                                        .addComponent(jTextField10, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
                                                                                .addComponent(jButton27, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jToggleButton2, GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                                                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
                                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        .addPreferredGap(ComponentPlacement.RELATED)
                                                                                        .addComponent(jTextField11, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(0, 2, Short.MAX_VALUE))
                                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        .addGap(7)
                                                                                        .addComponent(jButton28, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)))))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
                                                        .addComponent(jScrollPane1)
                                                        .addComponent(jTextField2, 468, 468, Short.MAX_VALUE))))
                                .addGap(32))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addGap(2)
                                                .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                                                .addComponent(jTextField10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7)))
                                .addGap(8)
                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(3)
                                                .addComponent(jLabel4))
                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                                                .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton38)
                                                .addComponent(jToggleButton2)
                                                .addComponent(jTextField11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                .addGap(16)
                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                        .addComponent(jButton27, GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                        .addComponent(jButton18, GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                                .addComponent(jButton20)
                                                                .addComponent(jButton21)
                                                                .addComponent(jButton17))
                                                        .addPreferredGap(ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                                                                .addComponent(jButton13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jButton12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jButton14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(jButton15, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton26, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton28, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18)
                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
                                        .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                        .addComponent(jButton8)
                                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                                                                .addComponent(jButton9)
                                                                .addComponent(jButton10)))
                                                .addGap(8)
                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jButton7)
                                                                .addGap(6)
                                                                .addComponent(jButton11, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jButton5)
                                                                        .addGap(6)
                                                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                                                                                .addComponent(jButton24)
                                                                                .addComponent(jButton2)
                                                                                .addComponent(jButton4))
                                                                        .addPreferredGap(ComponentPlacement.RELATED)
                                                                        .addComponent(jButton25, 0, 0, Short.MAX_VALUE))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jButton6)
                                                                        .addGap(35)
                                                                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                                                                                .addComponent(jButton1)
                                                                                .addComponent(jButton19))))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                                                        .addComponent(jButton29, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                                        .addComponent(jButton30, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton31, GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                                                .addPreferredGap(ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
                                                        .addComponent(jButton33, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton37, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton32, GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)))
                                        .addComponent(jButton16, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);
 
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
                layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);
 
        pack();
    }
 
    /**
     * IMP: Znak Delete
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {
        String tekst = jTextField2.getText();
        jTextField2.setText(tekst.substring(0, tekst.length() - 1));
    }
 
    /**
     * IMP: Liczba 2
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {
        String tekst = jTextField1.getText();
        if (tekst.equals("0"))
        {
            jTextField1.setText("2");
        }
        else
        {
            jTextField1.setText(tekst + "2");
        }
    }
 
    /**
     * IMP: Liczba 1
     */
    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        if (tekst.equals("0"))
        {
            jTextField1.setText("1");
        }
        else
        {
            jTextField1.setText(tekst + "1");
        }
    }
 
    /**
     * IMP: Znak "C"
     */
    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt)
    {
        jTextField1.setText("0");
        jTextField4.setText("");
    }
   
    /**
     * IMP: Znak ")"
     */
    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        String tekst2 = jTextField2.getText();
        String kropka = ".";
 
        if (tekst.endsWith(kropka))
        {
           jTextField1.setText(tekst.substring(0, tekst.length() - 1));
        }
 
        String tekst6 = jTextField1.getText();
        if (tekst2.length() > 3)
        {
            String tekst3 = tekst2 + " " + tekst6 + " " + ")";
            jTextField2.setText(tekst3);
            jTextField1.setText("0");
        }
        else
        {
            String tekst4 = ")";
            jTextField2.setText(tekst4);
            jTextField1.setText("0");
        }
        jTextField1.setText(null);
    }
 
    /**
     * IMP: Znak "("
     */
    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        String tekst2 = jTextField2.getText();
 
        if (tekst.equals("0"))
        {
            String tekst5 = tekst2 + " " + "(";
            jTextField2.setText(tekst5);
        }
        else
        {
            if (tekst2.length() > 1)
            {
                String tekst3 = tekst2 + " " + tekst + " " + "(";
                jTextField2.setText(tekst3);
                jTextField1.setText("0");
            }
            else
            {
                String tekst4 = "   " + "(" + " ";
                jTextField2.setText(tekst4);
                jTextField1.setText("0");
            }
        }
    }
 
    /**
     * IMP: Znak "CE"
     */
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt)
    {
        jTextField1.setText("0");
        jTextField2.setText("");
        jTextField4.setText("");
        jTextArea1.setText("");
        jTextField10.setText("pusta");
    }
 
    /**
     * IMP: Znak "%"
     */
    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String wartosc = jTextField1.getText();
        double wartoscD = Double.parseDouble(wartosc);
        double wynik = wartoscD / 100;
        jTextField1.setText(String.valueOf(wynik));
    }
 
    /**
     * IMP: Znak "sqrt"
     */
    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String wartosc = jTextField1.getText();
        double wartoscD = Double.parseDouble(wartosc);
        double wartoscSqrt = Math.sqrt(wartoscD);
        String tekst = "\u221a" + wartosc + " " + "=" + " ";
 
        String tekstArea = jTextArea1.getText();
 
        if (tekstArea.length() > 0)
        {
            jTextArea1.setText(tekstArea + '\n' + '\n' + tekst + String.valueOf(wartoscSqrt));
        }
        else
        {
            jTextArea1.setText(tekst + String.valueOf(wartoscSqrt));
        }
        jTextField2.setText("");
        jTextField1.setText("0");
        jTextField4.setText("");
    }
 
    /**
     * IMP: Znak "=" oraz ONP (odwrócona notacja polska w okienku "ONP"
     */
    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String pamiec = jTextField10.getText();
        String pamiec2 = jTextField2.getText();
        if (!pamiec.equals("pusta") && !pamiec2.endsWith("a") && !pamiec.equals("Sin") && !pamiec.equals("Cos") && !pamiec.equals("Tan") && !pamiec.equals("TanH") && !pamiec.equals("Exp") && !pamiec.equals("Log"))
        {
            String potega2 = jTextField2.getText();
            String power = "i";
            String powerMinus = "-";
 
            // <Funkcja potęgi>
            if (potega2.endsWith(power))
            {
                double wartosc2 = Double.parseDouble(jTextField1.getText());
                String tekst = jTextField10.getText();
                double wartosc = Double.parseDouble(tekst);
                double wynik = Math.pow(wartosc, wartosc2);
                String tekstArea = jTextArea1.getText();
 
                if (tekstArea.length() > 0)
                {
                    jTextArea1.setText(tekstArea + '\n' + '\n' + potega2 + " " + wartosc2 + " = " + String.valueOf(wynik));
                }
                else
                {
                    jTextArea1.setText(potega2 + " " + wartosc2 + " = " + String.valueOf(wynik));
                }
                jTextField2.setText("");
                jTextField1.setText("");
                jTextField4.setText("");
                jTextField10.setText("pusta");
            }
            else if (potega2.endsWith(powerMinus))
            {
                double wartosc2 = Double.parseDouble(jTextField1.getText());
                String tekst = jTextField1.getText();
                double wartosc = Double.parseDouble(tekst);
                double wynik = Math.pow(wartosc, -wartosc2);
                String tekstArea = jTextArea1.getText();
 
                if (tekstArea.length() > 0)
                {
                    jTextArea1.setText(tekstArea + '\n' + '\n' + potega2 + " " + wartosc2 + " = " + String.valueOf(wynik));
                }
                else
                {
                    jTextArea1.setText(potega2 + " " + wartosc2 + " = " + String.valueOf(wynik));
                }
                jTextField2.setText("");
                jTextField1.setText("");
                jTextField4.setText("");
                jTextField10.setText("pusta");
            }
        }
        // </Funkcja potęgi>
 
        // <Funkcja Sinus>
        if (pamiec.equals("Sin"))
        {
            double sinus = Double.parseDouble(jTextField1.getText());
            double wynik = Math.sin(sinus);
            String stopien = jTextField11.getText();
 
            if (stopien.equals("Deg"))
            {
                double wynikD = Math.toDegrees(wynik);
 
                String tekstArea = jTextArea1.getText();
 
                if (tekstArea.length() > 0)
                {
                    jTextArea1.setText(tekstArea + '\n' + '\n' + "Sin[deg](" + sinus + ") = " + wynikD);
                }
                else
                {
                    jTextArea1.setText("Sin[deg](" + sinus + ") = " + wynikD);
                }
                jTextField2.setText("");
                jTextField1.setText("");
                jTextField4.setText("");
                jTextField10.setText("pusta");
            }
            else
            {
                String tekstArea = jTextArea1.getText();
 
                if (tekstArea.length() > 0)
                {
                jTextArea1.setText(tekstArea + '\n' + '\n' + "Sin[rad](" + sinus + ") = " + wynik);
                }
                else
                {
                jTextArea1.setText("Sin[rad](" + sinus + ") = " +wynik);
                }
                jTextField2.setText("");
                jTextField1.setText("");
                jTextField4.setText("");
                jTextField10.setText("pusta");
            }
        }
        // </Funkcja Sinus>>
 
        // <Funkcja Cosinus>
        if (pamiec.equals("Cos"))
        {
            double cosinus = Double.parseDouble(jTextField1.getText());
            double wynik = Math.cos(cosinus);
            String stopien = jTextField11.getText();
 
            if (stopien.equals("Deg"))
            {
                double wynikD = Math.toDegrees(wynik);
 
                String tekstArea = jTextArea1.getText();
 
                if (tekstArea.length() > 0)
                {
                    jTextArea1.setText(tekstArea + '\n' + '\n' + "Cos[deg](" + cosinus + ") = " + wynikD);
                }
                else
                {
                    jTextArea1.setText("Cos[deg](" + cosinus + ") = " + wynikD);
                }
                jTextField2.setText("");
                jTextField1.setText("");
                jTextField4.setText("");
                jTextField10.setText("pusta");
            }
            else
            {
                String tekstArea = jTextArea1.getText();
 
                if (tekstArea.length() > 0)
                {
                jTextArea1.setText(tekstArea + '\n' + '\n' + "Cos[rad](" + cosinus + ") = " + wynik);
                }
                else
                {
                jTextArea1.setText("Cos[rad](" + cosinus + ") = " +wynik);
                }
                jTextField2.setText("");
                jTextField1.setText("");
                jTextField4.setText("");
                jTextField10.setText("pusta");
            }
        }
        // </Funkcja Cosinus>>
 
        // <Funkcja Tangens>
        if (pamiec.equals("Tan"))
        {
            double tangens = Double.parseDouble(jTextField1.getText());
            double wynik = Math.tan(tangens);
            String stopien = jTextField11.getText();
 
            if (stopien.equals("Deg"))
            {
                double wynikD = Math.toDegrees(wynik);
 
                String tekstArea = jTextArea1.getText();
 
                if (tekstArea.length() > 0)
                {
                    jTextArea1.setText(tekstArea + '\n' + '\n' + "Tan[deg](" + tangens + ") = " + wynikD);
                }
                else
                {
                    jTextArea1.setText("Tan[deg](" + tangens + ") = " + wynikD);
                }
                jTextField2.setText("");
                jTextField1.setText("");
                jTextField4.setText("");
                jTextField10.setText("pusta");
            }
            else
            {
                String tekstArea = jTextArea1.getText();
 
                if (tekstArea.length() > 0)
                {
                jTextArea1.setText(tekstArea + '\n' + '\n' + "Tan[rad](" + tangens + ") = " + wynik);
                }
                else
                {
                jTextArea1.setText("Tan[rad](" + tangens + ") = " +wynik);
                }
                jTextField2.setText("");
                jTextField1.setText("");
                jTextField4.setText("");
                jTextField10.setText("pusta");
            }
        }
        // </Funkcja Tangens>>
 
        // <Funkcja Tanh>
        if (pamiec.equals("TanH"))
        {
            double tanh = Double.parseDouble(jTextField1.getText());
            double wynik = Math.tanh(tanh);
            String stopien = jTextField11.getText();
 
            if (stopien.equals("Deg"))
            {
                double wynikD = Math.toDegrees(wynik);
 
                String tekstArea = jTextArea1.getText();
 
                if (tekstArea.length() > 0)
                {
                    jTextArea1.setText(tekstArea + '\n' + '\n' + "TanH[deg](" + tanh + ") = " + wynikD);
                }
                else
                {
                    jTextArea1.setText("TanH[deg](" + tanh + ") = " + wynikD);
                }
                jTextField2.setText("");
                jTextField1.setText("");
                jTextField4.setText("");
                jTextField10.setText("pusta");
            }
            else
            {
                String tekstArea = jTextArea1.getText();
 
                if (tekstArea.length() > 0)
                {
                jTextArea1.setText(tekstArea + '\n' + '\n' + "TanH[rad](" + tanh + ") = " + wynik);
                }
                else
                {
                jTextArea1.setText("TanH[rad](" + tanh + ") = " +wynik);
                }
                jTextField2.setText("");
                jTextField1.setText("");
                jTextField4.setText("");
                jTextField10.setText("pusta");
            }
        }
        // </Funkcja Tanh>>
 
        // <Funkcja Exp>
        if (pamiec.equals("Exp"))
        {
            double exp = Double.parseDouble(jTextField1.getText());
            double wynik = Math.exp(exp);
 
            String tekstArea = jTextArea1.getText();
 
            if (tekstArea.length() > 0)
            {
                jTextArea1.setText(tekstArea + '\n' + '\n' + "Exp(" + exp + ") = " + wynik);
            }
            else
            {
                jTextArea1.setText("Exp(" + exp + ") = " +wynik);
            }
            jTextField2.setText("");
            jTextField1.setText("");
            jTextField4.setText("");
            jTextField10.setText("pusta");
        }
        // </Funkcja Exp>>
 
        // <Funkcja Log>
        if (pamiec.equals("Log"))
        {
            double log = Double.parseDouble(jTextField1.getText());
            double wynik = Math.log(log);
 
            String tekstArea = jTextArea1.getText();
 
            if (tekstArea.length() > 0)
            {
                jTextArea1.setText(tekstArea + '\n' + '\n' + "Log(" + log + ") = " + wynik);
            }
            else
            {
                jTextArea1.setText("Log(" + log + ") = " +wynik);
            }
            jTextField2.setText("");
            jTextField1.setText("");
            jTextField4.setText("");
            jTextField10.setText("pusta");
        }
        // </Funkcja Log>>
 
        // <Funkcja Dzielenie Modulo>
        if (pamiec2.endsWith("a"))
        {
            double wartosc1 = Double.parseDouble(jTextField10.getText());
            double wartosc2 = Double.parseDouble(jTextField1.getText());
            double wynik = wartosc1 % wartosc2;
 
            String tekstArea = jTextArea1.getText();
 
            if (tekstArea.length() > 0 )
            {
                jTextArea1.setText(tekstArea + '\n' + '\n' + wartosc1 + " dzielone modulo na " + wartosc2 + " daje resztÄ™ = " + wynik);
            }
            else
            {
                jTextArea1.setText(wartosc1 + " dzielone modulo na " + wartosc2 + " daje resztÄ™ = " + wynik);
            }
            jTextField2.setText("");
            jTextField1.setText("");
            jTextField4.setText("");
            jTextField10.setText("pusta");
        }
        // </Funkcja Dzielenie Modulo>
 
        String pole1 = jTextField1.getText();
        String pole2 = jTextField2.getText();
        String pole1AND2Infiks = pole2 + " " + pole1;
        String pole1AND2Postfiks = "";
       
        Priorytet ustal = new Priorytet();
       
        Stack<String> stos;
        stos = new Stack();
        StringTokenizer st;
        st = new StringTokenizer(pole1AND2Infiks, " ");
 
        while (st.hasMoreTokens())
        {
            String s = st.nextToken();
           
            if (s.equals("+") || s.equals("*") || s.equals("-") || s.equals("/"))
            {
                while (!stos.empty() && ustal.priorytet(stos.peek()) >= ustal.priorytet(s))
                {
                    pole1AND2Postfiks += stos.pop() + " ";
                }
                stos.push(s);
            }
            else
            {
                if (s.equals("("))
                {
                    stos.push(s);
                }
                else
                {
                    if (s.equals(")"))
                    {
                        while (!stos.peek().equals("("))
                        {
                            pole1AND2Postfiks += stos.pop() + " ";
                        }
                        stos.pop();
                    }
                    else
                    {
                        pole1AND2Postfiks += s + " ";
                    }
                }
            }
        }
        while (!stos.empty())
        {
            pole1AND2Postfiks += stos.pop() + " ";
        }
        jTextField4.setText(pole1AND2Postfiks);
 
 
        Stack<Double> stos2 = new Stack<Double>();
        StringTokenizer st2 = new StringTokenizer(pole1AND2Postfiks, " ");
 
        while (st2.hasMoreTokens())
        {
            String s2 = st2.nextToken();
 
            if (!s2.equals("+") && !s2.equals("*") && !s2.equals("-") && !s2.equals("/"))
            {
                double wartosc = Double.parseDouble(s2);
                stos2.push(wartosc);
            }
            else
            {
                double wartosc1 = stos2.pop();
                double wartosc2 = stos2.pop();
                switch (s2.charAt(0))
                {
                    case '*':
                    {
                        stos2.push(wartosc2 * wartosc1);
                        break;
                    }
                    case '+':
                    {
                        stos2.push(wartosc2 + wartosc1);
                        break;
                    }
                    case '-':
                    {
                        stos2.push(wartosc2 - wartosc1);
                        break;
                    }
                    case '/':
                    {
                        stos2.push(wartosc2 / wartosc1);
                        break;
                    }
                }
            }
        }
        double wynik = stos2.pop();
 
        String tekst1 = jTextField1.getText();
        String tekst2 = jTextField2.getText();
        String tekst2wynik = tekst2 + " " + tekst1 + " " + "=" + " ";
        jTextField2.setText(tekst2wynik + String.valueOf(wynik));
        jTextField1.setText(String.valueOf(wynik));
        String tekstArea = jTextArea1.getText();
 
        if (tekstArea.length() > 0)
        {
            jTextArea1.setText(tekstArea + '\n' + '\n' + tekst2wynik + String.valueOf(wynik));
        }
        else
        {
            jTextArea1.setText(tekst2wynik + String.valueOf(wynik));
        }
        jTextField2.setText("");
        jTextField1.setText("0");
    }
 
    /**
     * IMP: Znak "+"
     */
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        String tekst2 = jTextField2.getText();
        String kropka = ".";
 
        if (tekst.endsWith(kropka))
        {
           jTextField1.setText(tekst.substring(0, tekst.length() - 1));
        }
 
        String tekst6 = jTextField1.getText();
 
        if (tekst6.equals("0"))
        {
            String tekst5 = tekst2 + " " + "+";
            jTextField2.setText(tekst5);
        }
        else
        {
            if (tekst2.length() > 3)
            {
                String tekst3 = tekst2 + " " + tekst6 + " " + "+";
                jTextField2.setText(tekst3);
                jTextField1.setText("0");
            }
            else
            {
                String tekst4 = tekst2 + " " + tekst6 + " " + "+";
                jTextField2.setText(tekst4);
                jTextField1.setText("0");
            }
        }
    }
 
    /**
     * IMP: Znak "-"
     */
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        String tekst2 = jTextField2.getText();
        String kropka = ".";
        String power = "r";
        String modulo = "a";
 
        if (tekst2.endsWith(power))
        {
            jTextField2.setText(tekst2 + " " + "-");
        }
 
        if (tekst2.endsWith(modulo))
        {
            jTextField2.setText("Niestety nie podzielisz przez liczbÄ™ ujemnÄ… ;/");
        }
 
        if (tekst.endsWith(kropka))
        {
           jTextField1.setText(tekst.substring(0, tekst.length() - 1));
        }
 
        String tekst6 = jTextField1.getText();
 
        if (tekst6.equals("0") && !tekst2.endsWith(power) && !tekst2.endsWith(modulo))
        {
            String tekst5 = tekst2 + " " + "-";
            jTextField2.setText(tekst5);
        }
        else
        {
            if (tekst2.length() > 3 && !tekst2.endsWith(power) && !tekst2.endsWith(modulo))
            {
                String tekst3 = tekst2 + " " + tekst6 + " " + "-";
                jTextField2.setText(tekst3);
                jTextField1.setText("0");
            }
            else if (!tekst2.endsWith(power) && !tekst2.endsWith(modulo))
            {
                String tekst4 = tekst2 + " " + tekst6 + " " + "-";
                jTextField2.setText(tekst4);
                jTextField1.setText("0");
            }
        }
    }
 
    /**
     * IMP: Znak "*"
     */
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        String tekst2 = jTextField2.getText();
        String kropka = ".";
 
        if (tekst.endsWith(kropka))
        {
           jTextField1.setText(tekst.substring(0, tekst.length() - 1));
        }
 
        String tekst6 = jTextField1.getText();
 
        if (tekst6.equals("0"))
        {
            String tekst5 = tekst2 + " " + "*";
            jTextField2.setText(tekst5);
        }
        else
        {
            if (tekst2.length() > 3)
            {
                String tekst3 = tekst2 + " " + tekst6 + " " + "*";
                jTextField2.setText(tekst3);
                jTextField1.setText("0");
            }
            else
            {
                String tekst4 = tekst2 + " " + tekst6 + " " + "*";
                jTextField2.setText(tekst4);
                jTextField1.setText("0");
            }
        }
    }
 
    /**
     * IMP: Znak "/"
     */
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        String tekst2 = jTextField2.getText();
        String kropka = ".";
 
        if (tekst.endsWith(kropka))
        {
           jTextField1.setText(tekst.substring(0, tekst.length() - 1));
        }
 
        String tekst6 = jTextField1.getText();
 
        if (tekst6.equals("0"))
        {
            String tekst5 = tekst2 + " " + "/";
            jTextField2.setText(tekst5);
        }
        else
        {
            if (tekst2.length() > 3)
            {
                String tekst3 = tekst2 + " " + tekst6 + " " + "/";
                jTextField2.setText(tekst3);
                jTextField1.setText("0");
            }
            else
            {
                String tekst4 = tekst2 + " " + tekst6 + " " + "/";
                jTextField2.setText(tekst4);
                jTextField1.setText("0");
            }
        }
    }
 
    /**
     * IMP: Liczba 9
     */
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        if (tekst.equals("0"))
        {
            jTextField1.setText("9");
        }
        else
        {
            jTextField1.setText(tekst + "9");
        }
    }
 
    /**
     * IMP: Liczba 8
     */
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        if (tekst.equals("0"))
        {
            jTextField1.setText("8");
        }
        else
        {
            jTextField1.setText(tekst + "8");
        }
    }
 
    /**
     * IMP: Liczba 7
     */
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        if (tekst.equals("0"))
        {
            jTextField1.setText("7");
        }
        else
        {
            jTextField1.setText(tekst + "7");
        }
    }
 
    /**
     * IMP: Liczba 6
     */
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        if (tekst.equals("0"))
        {
            jTextField1.setText("6");
        }
        else
        {
            jTextField1.setText(tekst + "6");
        }
    }
 
    /**
     * IMP: Liczba 5
     */
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        if (tekst.equals("0"))
        {
            jTextField1.setText("5");
        }
        else
        {
            jTextField1.setText(tekst + "5");
        }
    }
 
    /**
     * IMP: Liczba 4
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        if (tekst.equals("0"))
        {
            jTextField1.setText("4");
        }
        else
        {
            jTextField1.setText(tekst + "4");
        }
    }
 
    /**
     * IMP: Liczba 3
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        if (tekst.equals("0"))
        {
            jTextField1.setText("3");
        }
        else
        {
            jTextField1.setText(tekst + "3");
        }
    }
 
    /**
     * IMP: Liczba 0
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        if (tekst.equals("0"))
        {
            jTextField1.setText("0");
            jTextField2.setText("0");
        }
        else
        {
            jTextField1.setText(tekst + "0");
        }
    }
 
    /**
     * IMP: Znak "."
     */
    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt)
    {
        Kropka ustal = new Kropka();
        String tekst2 = jTextField1.getText();
 
        if (ustal.czyKropka(tekst2) == 1 || ustal.czyKropka(tekst2) == 0)
        {
            String tekst = jTextField1.getText();
            jTextField1.setText(tekst + ".");
        }
    }
 
    /**
     * IMP: Liczba Pi
     */
    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst2 = jTextField2.getText();
        String power = "r";
 
        // <Funkcja potęgi>
        if (tekst2.endsWith(power))
        {
            String tekst = jTextField1.getText();
            double wartosc = Double.parseDouble(tekst);
            double wynik = Math.pow(wartosc, 3.1415);
            String tekstArea = jTextArea1.getText();
 
            if (tekstArea.length() > 0)
            {
                jTextArea1.setText(tekstArea + '\n' + '\n' + tekst2 + " " + "Pi(3.1415) = " + String.valueOf(wynik));
            }
            else
            {
                jTextArea1.setText(tekst2 + " " + "Pi(3.1415) = " + String.valueOf(wynik));
            }
            jTextField2.setText("");
            jTextField1.setText("0");
        }
        // </Funkcja potęgi>
 
        jTextField1.setText("0");
        String tekst = jTextField1.getText();
        if (tekst.equals("0"))
        {
            jTextField1.setText("3.1415");
        }
    }
 
    /**
     * IMP: Funkcja potęgowania
     */
    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        if (tekst.equals(""))
        {
            jTextField2.setText("Nie podaĹ‚eĹ› ĹĽadnej wartoĹ›ci Num!");
        }
        else
        {
            jTextField2.setText("");
            jTextField2.setText("Num" + " " + tekst + " " + " " + "do potÄ™gi");
            jTextField10.setText(tekst);
            jTextField1.setText("0");
        }
    }
 
    /**
     * IMP: Funkcja sinus
     */
    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt)
    {
        jTextField2.setText("Sin(podaj liczbÄ™)");
        jTextField10.setText("Sin");
        jTextField1.setText("0");
    }
 
    /**
     * IMP: Funkcja cosinus
     */
    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt)
    {
        jTextField2.setText("Cos(podaj liczbÄ™)");
        jTextField10.setText("Cos");
        jTextField1.setText("0");
    }
 
    /**
     * IMP: Funkcja tangens
     */
    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt)
    {
 
        jTextField2.setText("Tan(podaj liczbÄ™)");
        jTextField10.setText("Tan");
        jTextField1.setText("0");
    }
 
    /**
     * IMP: Funkcja tanh
     */
    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt)
    {
        jTextField2.setText("TanH(podaj liczbÄ™)");
        jTextField10.setText("TanH");
        jTextField1.setText("0");
    }
 
    /**
     * IMP: Funkcja exp
     */
    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt)
    {
        jTextField2.setText("Exp(podaj liczbÄ™)");
        jTextField10.setText("Exp");
        jTextField1.setText("0");
    }
 
    /**
     * IMP: Funkcja Log
     */
    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt)
    {
        jTextField2.setText("Log(podaj liczbÄ™)");
        jTextField10.setText("Log");
        jTextField1.setText("0");
    }
 
    /**
     * IMP: Funkcja dzielenie modulo
     */
    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt)
    {
        String tekst = jTextField1.getText();
        if (tekst.equals(""))
        {
            jTextField2.setText("Nie podaĹ‚eĹ› ĹĽadnej wartoĹ›ci Num!");
        }
        else
        {
            jTextField2.setText("");
            jTextField2.setText("Num" + " " + tekst + " " + " " + "dzielone modulo na");
            jTextField10.setText(tekst);
            jTextField1.setText("0");
        }
    }
 
    /**
     * IMP: Radiany
     */
    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt)
    {
        jTextField11.setText("Rad");
    }
 
    /**
     * IMP: Stopnie
     */
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt)
    {
        jTextField11.setText("Deg");
    }
 
    public static void main(String args[])
    {
        try
                {
                    UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
                }
                catch (Exception e)
                {
                    System.out.println(e);
                }
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new kalkulator().setVisible(true);
 
 
            }
        });
    }
    // Variables declaration - do not modify (NetBeans Shit...)
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration (NetBeans Shit...)
}